spring:
  application:
    name: spring-cloud-gateway
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8080
      # 服务启动直接建立心跳连接
      eager: true
    gateway:
      routes:
        - id: hi
          uri:  lb://SERVICE-DEMO
          predicates:
            - Path=/hi
      discovery:
        locator:
          enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka
    instance:
      prefer-ip-address: true
ribbon:
  eureka:
    enabled: false
order-service:
  ribbon:
    listOfServers: localhost:8701, localhost:8702
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
logging:
  level:
    org.springframework.cloud.gateway: debug
server:
  port: 8703
