
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/an137699686/spring-cloud/spring-server
          basedir: config-server/target
          default-label: main
  application:
    name: config-server
server:
  port: 8888
