
spring:
  cloud:
    config:
      server:
        git:
          uri: file://D:/learn/env
#       git:
#          uri: https://github.com/an137699686/spring-cloud
#          basedir: config-server/target
#          default-label: main
  application:
    name: config-server
server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
