server:
  port: 8702

spring:
  application:
    name: service-demo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka
    instance:
      hostname: localhost
      instance-id: ${spring.application.name}:${random.int}